services:
  db:
    image: mysql
    restart: always
    env_file: .env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./simos:/var/lib/mysql